import '@/styles/globals.css'
import { Metadata, Viewport } from "next";
import { Inter, Amiri } from "next/font/google";
import { Providers } from "@/components/providers/providers";

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-sans',
  display: 'swap',
})

const amiri = Amiri({
  subsets: ['arabic', 'latin'],
  weight: ['400', '700'],
  variable: '--font-arabic',
  display: 'swap',
})

export const metadata: Metadata = {
  title: {
    default: 'Quran App - Read, Learn, Listen, and Focus',
    template: '%s | Quran App',
  },
  description: 'An accessible and beautiful way to read, listen to, and learn the Quran. | Generated by Next.js',
  keywords: [
    "Quran",
    "Islam",
    "Arabic",
    "Recitation",
    "Learning",
    "Religious",
    "Muslim",
    "Holy Book"
  ],
  authors: [
    {
      name: 'Quran App Team'
    }
  ],
  metadataBase: new URL(process.env.NEXT_PUBLIC_APP_URL || 'http://localhost:3000'),
  openGraph: {
    type: 'website',
    locale: 'en-US'
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    }
  },
  manifest: '/manifest.json',
  icons: {
    icon: '/favicon.ico',
    shorcut: '/favicon-16x16.png',
    apple: '/apple-touch-icon.png',
  },
};

export const viewport : Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 5,
  userScalable: true,
  themeColor: [
    {
      media: '(prefers-color-schema: light)', color: '#ffffff',
    },
    {
      media: '(prefers-color-schema: dark)', color: '#0a0a0a', // not to dark
    },
  ],
  colorScheme: 'light dark',
}

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html 
      lang="en"
      dir="ltr" // left to right
      suppressHydrationWarning
      className={`${inter.variable} ${amiri.variable}`}
    >
      <head>
        <link rel="preconnect" href="https://fonts.google.apis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin='anonymous'/>
        <link rel="preconnect" href="https://api.quran.gading.dev"/>

        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="default" />
        <meta name="apple-mobile-web-app-title" content="Quran App" />
        <meta name="apple-web-app-capable" content="yes" />
        <meta name="msapplication-TileColor" content="#047857" />
        <meta name="msapplication-tap-highlight" content="no" />
      </head>

      <body
        className='min-h-screen bg-background font-sans antialiased'
        suppressHydrationWarning
      >
        <Providers>
          <div className='relative flex min-h-screen flex-col'>
            <main className='flex-1'>
              {children}
            </main>
          </div>
        </Providers>

        {/* Service Worker Registration */}
      
      </body>
    </html>
  )
}
