import '@/styles/globals.css'
import { Metadata, Viewport } from "next";
import { Inter, Amiri } from "next/font/google";

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-sans',
  display: 'swap',
})

const amiri = Amiri({
  subsets: ['arabic', 'latin'],
  weight: ['400', '700'],
  variable: '--font-arabic',
  display: 'swap',
})

export const metadata = {
  title: {
    default: 'Quran App - Read, Learn, Listen, and Focus',
    template: '%s | Quran App',
  },
  description: 'An accessible and beautiful way to read, listen to, and learn the Quran. | Generated by Next.js',
  keywords: [
    "Quran",
    "Islam",
    "Arabic",
    "Recitation",
    "Learning",
    "Religious",
    "Muslim",
    "Holy Book"
  ],
  authors: [
    {
      name: 'Quran App Team'
    }
  ],
  metadataBase: new URL(process.env.NEXT_PUBLIC_APP_URL || 'http://localhost:3000'),
  openGraph: {
    type: 'website',
    locale: 'en-US'
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    }
  },
  manifest: '/manifest.json',
  icons: {
    icon: '/favicon.ico',
    shorcut: '/favicon-16x16.png',
    apple: '/apple-touch-icon.png',
  },
};

export const viewport : Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 5,
  userScalable: true,
  themeColor: [
    {
      media: '(prefers-color-schema: light)', color: '#ffffff',
    },
    {
      media: '(prefers-color-schema: dark)', color: '#0a0a0a', // not to dark
    },
  ],
  colorScheme: 'light dark',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
